package com.today.api.user.response

/**
         * Autogenerated by Dapeng-Code-Generator (1.2.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated

        *

 分页查询用户操作返回体

        **/
        case class FindUserByPageResponse(

         /**
        *

 用户 id

        **/
        
        pageResponse : com.today.api.page.TPageResponse, /**
        *

 用户列表

        **/
        
        userList : List[com.today.api.user.dto.TUser]
        )
      