 package com.today.api.user.request.serializer

import com.today.api.user.dto.serializer._;import com.today.api.user.request.serializer._;import com.today.api.user.response.serializer._;import com.today.api.page.serializer._;
        import com.isuwang.dapeng.core._
        import com.isuwang.org.apache.thrift._
        import com.isuwang.org.apache.thrift.protocol._

        /**
        * Autogenerated by Dapeng-Code-Generator (1.2.2)
        *
        * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
        *  @generated
        **/

        class FindUserByPageRequestSerializer extends TCommonBeanSerializer[com.today.api.user.request.FindUserByPageRequest]{
          
      @throws[TException]
      override def read(iprot: TProtocol): com.today.api.user.request.FindUserByPageRequest = {

        var schemeField: com.isuwang.org.apache.thrift.protocol.TField = null
        iprot.readStructBegin()

      var pageRequest: com.today.api.page.TPageRequest = null
        var integral: Int = 0
        var userStatus: com.today.api.user.enums.UserStatusEnum = null
        

      while (schemeField == null || schemeField.`type` != com.isuwang.org.apache.thrift.protocol.TType.STOP) {

        schemeField = iprot.readFieldBegin

        schemeField.id match {
          
              case 1 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.STRUCT => pageRequest = new com.today.api.page.serializer.TPageRequestSerializer().read(iprot)
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
              case 2 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.I32 => integral = iprot.readI32
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
              case 3 =>
                  schemeField.`type` match {
                    case com.isuwang.org.apache.thrift.protocol.TType.I32 => userStatus = com.today.api.user.enums.UserStatusEnum.findByValue(iprot.readI32)
                    case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
            }
            
          case _ => com.isuwang.org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.`type`)
        }
      }

      iprot.readFieldEnd
      iprot.readStructEnd

      val bean = com.today.api.user.request.FindUserByPageRequest(pageRequest = pageRequest,integral = integral,userStatus = userStatus)
      validate(bean)

      bean
      }
    
      @throws[TException]
      override def write(bean: com.today.api.user.request.FindUserByPageRequest, oprot: TProtocol): Unit = {

      validate(bean)
      oprot.writeStructBegin(new com.isuwang.org.apache.thrift.protocol.TStruct("FindUserByPageRequest"))

      
            {
            val elem0 = bean.pageRequest 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("pageRequest", com.isuwang.org.apache.thrift.protocol.TType.STRUCT, 1.asInstanceOf[Short]))
             new com.today.api.page.serializer.TPageRequestSerializer().write(elem0, oprot)
            oprot.writeFieldEnd
            
            }
            {
            val elem1 = bean.integral 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("integral", com.isuwang.org.apache.thrift.protocol.TType.I32, 2.asInstanceOf[Short]))
            oprot.writeI32(elem1)
            oprot.writeFieldEnd
            
            }
            {
            val elem2 = bean.userStatus 
            oprot.writeFieldBegin(new com.isuwang.org.apache.thrift.protocol.TField("userStatus", com.isuwang.org.apache.thrift.protocol.TType.I32, 3.asInstanceOf[Short]))
            oprot.writeI32(elem2.id)
            oprot.writeFieldEnd
            
            }
      oprot.writeFieldStop
      oprot.writeStructEnd
    }
    
      @throws[TException]
      override def validate(bean: com.today.api.user.request.FindUserByPageRequest): Unit = {
      
              if(bean.pageRequest == null)
              throw new SoaException(SoaBaseCode.NotNull, "pageRequest字段不允许为空")
            
                if(bean.pageRequest != null)
                new com.today.api.page.serializer.TPageRequestSerializer().validate(bean.pageRequest)
              
              if(bean.userStatus == null)
              throw new SoaException(SoaBaseCode.NotNull, "userStatus字段不允许为空")
            
    }
    

          @throws[TException]
          override def toString(bean: com.today.api.user.request.FindUserByPageRequest): String = if (bean == null) "null" else bean.toString

        }
        
      