package com.today.api.user.dto

/**
 * Autogenerated by Dapeng-Code-Generator (1.2.2)
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*  @generated

*
**/
case class TIntegralJournal(

 /**
*

利用主键策略生成的唯一键

**/

id : Int, /**
*

用户名

**/

userId : Int, /**
*

流水类型,1:增加流水(add);2:减少流水(minus)

**/

integralType : Int, /**
*

当前流水涉及到的积分值

**/

integralPrice : Int, /**
*

流水来源,1:完善个人资料(prefect_information);2:拉黑(black)

**/

integralSource : Int, /**
*

用户当前的积分值

**/

integral : Int, /**
*

创建时间

**/

createdAt : Long, /**
*

特指后台创建人(公司员工 id)

**/

createdBy : Int, /**
*

更新时间

**/

updatedAt : Long, /**
*

特指后台更新人(公司员工 id)

**/

updatedBy : Int, /**
*

备注

**/

remark : String
)
      